#!/usr/bin/env bash
# generate key (should have even first hex value)
export NEW_KEY=`openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`

# disassociate old address/hardware
sudo /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -z

# set new address
sudo ifconfig en0 ether $NEW_KEY

# reassociate hardware
sudo networksetup -detectnewhardware
