#!/usr/bin/env bash

# disassociate old address/hardware
sudo /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -z

# set new address
# generate key (should have even first hex value)
NEW_KEY=`openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`
sudo ifconfig en0 ether $NEW_KEY

# generate key (should have even first hex value)
NEW_KEY=`openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`
sudo ifconfig en1 ether $NEW_KEY

# reassociate hardware
sudo networksetup -detectnewhardware
